name: 
  de: Ernesto Castillo
  fr: Ernesto Castillo
subtitle: 
  de: mots el son
  fr: mots el son
description: 
  de: mots el son - Offizielle Webseite des Autoren
  fr: mots el son - Site officiel de l'auteur
keywords: 
  de: Autor,Schriftsteller,Poet,Lyrik,Gedichte,Musik,Künstler
  fr: Auteur,Ecrivain,Poète,Poésie,Musique,Artiste
footer:
  de: Alle Inhalte von [Ernesto Castillo](/about/) © 2023
  fr: Tous les contenus [Ernesto Castillo](/fr/about/) © 2023
exclude: [README.md, _images-alt, _galeries-alt]
permalink: pretty
repository: https://github.com/nomadedaemon/nomadedaemon.github.io
# baseurl: https://nomadedaemon.github.io
productionurl: https://nomadedaemon.github.io
