name: 
  de: Ernesto Castillo
  fr: Ernesto Castillo
description: 
  de: mots el son
  fr: mots el son
footer:
  de: Alle Inhalte von [Ernesto Castillo](https://www.nomade-daemon.com)
  fr: Contenu du [Ernesto Castillo](https://www.nomade-daemon.com)
exclude: [README.md]
permalink: pretty
repository: mrzool/polyglot-jekyll
baseurl: https://nomadedaemon.github.io
