name: 
  de: Ernesto Castillo
  fr: Ernesto Castillo
description: 
  de: mots el son
  fr: mots el son
footer:
  de: Alle Inhalte von [Ernesto Castillo](https://nomadedaemon.github.io){:target="_blank"}
  fr: Contenu du [Ernesto Castillo](https://nomadedaemon.github.io){:target="_blank"}
exclude: [README.md]
permalink: pretty
repository: https://github.com/nomadedaemon/nomadedaemon.github.io
baseurl: https://nomadedaemon.github.io
