name: 
  de: Ernesto Castillo
  fr: Ernesto Castillo
description: 
  de: mots el son
  fr: mots el son
footer:
  de: Alle Inhalte von [Ernesto Castillo](/about/) © 2017
  fr: Tous les contenus [Ernesto Castillo](/fr/about/) © 2017
exclude: [README.md]
permalink: pretty
repository: https://github.com/nomadedaemon/nomadedaemon.github.io
# baseurl: https://nomadedaemon.github.io
