name: 
  de: Ernesto Castillo
  fr: Ernesto Castillo
subtitle: 
  de: mots el son
  fr: mots el son
description: 
  de: mots el son - Offizielle Webseite des Autoren
  fr: mots el son - Site officiel de l'auteur
keywords: 
  de: Autor,Schriftsteller,Lyrik,Gedichte,Musik,Künstler,Künstler
  fr: Auteur,Artiste,Ecrivain,Poète,Poésie,Musique,Artiste
footer:
  de: Alle Inhalte von [Ernesto Castillo](/about/) © 2017
  fr: Tous les contenus [Ernesto Castillo](/fr/about/) © 2017
exclude: [README.md]
permalink: pretty
repository: https://github.com/nomadedaemon/nomadedaemon.github.io
# baseurl: https://nomadedaemon.github.io
